### ISSUE TITLE
Create a language switcher

### ISSUE THREAD

**Issue by sdras** [sdras/array-explorer#11]
There's been a lot of interest supporting a bunch of different languages, and the first PR is in, so I need to build out a language switcher for the repo.

**Comment by AWolf81** [comment]
You could use this [vuex-i18n](https://github.com/dkfbasel/vuex-i18n) library.

There is also a different [github repo - vue-i18n](https://github.com/kazupon/vue-i18n) but I think the Vuex store approach is better suitable as you're having most of your text in the store.

Setup is pretty easy. Not sure if there is a better approach to implement it. It was my first search result after googling for `vue i18n`.

I've create a quick demo [here](https://codesandbox.io/s/82o712nr89).

If you need language support, please let me know. I could help with the German translation.

**Comment by sdras** [comment]
Excellent! Thank you for this.

**Comment by pachonk** [comment]
Hi there.
Is this a language switcher for programming languages or for for actual languages (English, French, etc)
If this is for languages, I would be more than happy to help with the Ruby translations

**Comment by sdras** [comment]
Hi @pachonk! This is currently for other actual languages, but I am making an object explorer that should be done in the next day or so, so you can see how to set it up for things like Ruby. If you fork it to make something like that, let me know and I'll link it up in the readme! I have to think about how it would be best for people to explore the explorers :)

**Comment by sdras** [comment]
It's in! 🎉
