### ISSUE TITLE
Write up sort() caveat

### ISSUE THREAD

**Issue by sdras** [sdras/array-explorer#12]
Sort should have a warning like the MDN docs

**Comment by stephenlcurtis** [comment]
Like how it sorts in place, the sort is unstable, and it uses unicode value so numeric sorting requires it's own comparator? Would it be helpful to allow them to select the kind of sort they want to do, then provide the standard numeric comparator if they want to sort numeric values.

**Comment by sdras** [comment]
Hi @stephenlcurtis, thanks for your willingness to collaborate on this.This isn't documentation, though. This is a way to explore that guides you to documentation, so I won't be clarifying as thoroughly as that, I'm going to mention that there are some caveats, such as the one mentioned when I opened the issue, and point to the documentation. Thanks though.

**Comment by sdras** [comment]
This is done!
