### ISSUE TITLE
Feature request: Syntax highlight the code example

### ISSUE THREAD

**Issue by SLaks** [sdras/array-explorer#16]
I find that syntax highlighting makes code easier / faster to mentally parse.

**Comment by sdras** [comment]
I did that for a bit but it's complicated with the animation because of the way the letters have to wrap. I eventually decided having the code progress on the screen was more important to cognitive load than the syntax highlighting.

**Comment by SLaks** [comment]
Why is it complicated?

You should be able to wrap each character from each styled <span> in an element and animate as before.
Or does SplitText ignore nested styles?

**Comment by sdras** [comment]
Yeah, splitText splits the spans and jacks up formatting. I can probably figure it out, it's just more time that I don't have right now. The highlighting is still in the package.json, so if you want a crack at  it, I can open this issue up and accept a PR from you, but I don't personally have the time to implement it right now.
