### ISSUE TITLE
Experiments with the snippet

### ISSUE THREAD

**Issue by arctarus44** [sdras/array-explorer#20]
Hi

Maybe you should allow user to play and experiments with snippet in "usage" and see the result in "output". So new javascript user could easily try these functions.

**Comment by sdras** [comment]
It's a good idea! It would mean reimplementing some stuff, so this would be a longer haul kind of feature. I like it though.

**Comment by Gonzalo2310** [comment]
A quick way would be links to examples in codepen or jsfiddle for example. That's where the little code would be and they'd play with it.

**Comment by terabaud** [comment]
I love the idea :) maybe just provide a button to [prefill a new pen](https://blog.codepen.io/documentation/api/prefill/) with the snippet code.

**Comment by arctarus44** [comment]
@Gonzalo2310 @Daniel-Griffiths using codepen or any similar tools could be a good start.

But, I think it's a bit too much for few lines of code. Beside, my idea was to keep the user on the same page, so he did not have to close a tab in order to find another function which will make his user experience more pleasant

**Comment by sdras** [comment]
His or her :)

I like all of these ideas. I agree keeping people on the page is good, but could also see where prefilling a pen could be useful. Right now I'm focusing on getting the language switcher in and an object explorer released, but I could definitely think about this for v2.

Thanks everyone!

**Comment by AWolf81** [comment]
I've tried to add an embedded codepen / jsbin etc. but it wasn't working like I wanted it.

How about a browser console with a sandbox that's running the entered code? 

Please have a look at the codesandbox [here](https://codesandbox.io/s/9lp07zllo).
It's using `@nx-js/compiler-util` as compiler for the sandboxed code execution.

I would enable that mode after clicking on an edit icon - so we can leave the nice animation effect and simply replace the input & output with the live editing feature.

Should I implement it like this?

**Comment by sdras** [comment]
Hey @AWolf81! Thanks for your time digging in.

It's a nice idea but it doesn't really fail well that I saw, I was in the middle of typing two characters here's just a portion of what was shown:

<img width="501" alt="screen shot 2017-12-31 at 8 28 14 am" src="https://user-images.githubusercontent.com/2281088/34462619-0083fe14-ee05-11e7-8507-e0954e3dc62f.png">

I'm starting to think that making the code editable is a bit overengineered for a project like this. I was considering Zed Shaw's _Learn Python The Hard Way_, and how he talks about how typing things out yourself is the most helpful exercise. I tend to agree with that, if people really want to learn, popping open the browser console and retyping the code here (it's not that much) to play with it might actually serve them best.

I'm going to close this out for now, but know that I don't feel that strongly either way, and that if people really feel it's necessary and find a way to execute in a way that doesn't take away from the project, I'm all ears. Happy new years!
