### ISSUE TITLE
[bug] indexOf is being used instead of lastIndexOf

### ISSUE THREAD

**Issue by trusktr** [sdras/array-explorer#23]
In the codepen, for the choice "find items", "one item", "the last index of a particular item" the example is using `indexOf` instead of `lastIndexOf`.

**Comment by sdras** [comment]
thanks, this is already fixed, I have a couple more PRs to merge and then I'll update the codepen :)

**Comment by trusktr** [comment]
oh ok, cool!

**Comment by sdras** [comment]
leaving this open until the codepen is all set, just to remind myself :)

**Comment by sdras** [comment]
Codepen updated :)
