### ISSUE TITLE
UX improvement: display as list instead of dropdown

### ISSUE THREAD

**Issue by phannam1412** [sdras/array-explorer#24]
Hi, when I choose a dropdown, then I need to click on another dropdown to see the full list, it's quite inconvenient. 
I think it's better that when I choose a dropdown, it will display the next list on UI (e.g. with ul li tags) so that I can view and can click to choose the option.

**Comment by sdras** [comment]
Thanks for stopping by! I disagree, though, I quite like it as a dropdown.
