### ISSUE TITLE
Amazing tool!!! URL params as a feature?

### ISSUE THREAD

**Issue by chrisopedia** [sdras/array-explorer#26]
I was hoping to turn this tool into an Alfred extension, and the only way I can see to do that is to possibly deal with query params from the URL.  Would you be interested in adding this to the current version? 

Something like selecting "I would like to "add…" and "element/s to an array" would result in the URL as follows: `https://sdras.github.io/array-explorer/add/?splice`.  Thoughts?

**Comment by sdras** [comment]
Hmmm, I almost feel like since this is an exploratory tool and not a reference, that you might want to use the taxonomy in what you're building and end up at the MDN docs? That might be more helpful to people. What do you think?

**Comment by sdras** [comment]
Ok, haven't heard back for about a week so I'm closing this out. Feel free to let me know if you nwat to discuss more

**Comment by geoffreyyip** [comment]
I agree with @chrisopedia. 

Your website is succinct. During a code review today, I noticed a coworker using `array.indexOf(item) > -1` to check if an item exists in an array. I could have linked them to the official MDN docs, but it's much easier to point them to your website.

So far, I've been taking pics and pasting them in Slack, but having route-able links would be great.

**Comment by chrisopedia** [comment]
@sdras sorry for the delay.  I'm not trying to change around the tool, just add the ability to call it from alfred tool since i'll most likely forget to load up the page.
