### ISSUE TITLE
typo bug

### ISSUE THREAD

**Issue by gentilmente** [sdras/array-explorer#28]
In codepen...
<img width="1195" alt="captura de pantalla 2017-12-29 a la s 10 05 32" src="https://user-images.githubusercontent.com/993201/34437925-8525f15c-ec81-11e7-9995-9796fef8b1fe.png">
but I saw code is ok. ¯\_(ツ)_/¯

**Comment by sdras** [comment]
Yeah, it's fixed, I'm just trying to get a few more PRs in, including the language switcher, before I rebuild it and bring everything over. Thanks!
