### ISSUE TITLE
Usage and Output animation is not visible

### ISSUE THREAD

**Issue by wopian** [sdras/array-explorer#35]
`scale: 0` from [this line](https://github.com/sdras/array-explorer/blob/724c1cb85aae68fb37a27e8a8ca4e99adc38e2e1/docs/static/css/app.b9d90eb0c9feb07cbad70eb503db37c1.css#L208) hides the animation and content. 

![chrome_2017-12-29_19-50-58](https://user-images.githubusercontent.com/3440094/34446330-0740e444-ecd2-11e7-8c76-24c7fb6537a2.png)

Removing it with dev tools shows the animation as intended.

![](https://thumbs.gfycat.com/FantasticSpicyIndianringneckparakeet-max-14mb.gif)

OS: Windows 10
Browser: Chrome 65

**Comment by welll** [comment]
@wopian  I think this PR https://github.com/sdras/array-explorer/pull/29/files already fixed

**Comment by sdras** [comment]
Yeah this is already fixed, I'm just waiting on a couple PRs to finish the language switcher to rebuild the docs. It's only affecting a small amount of people right now so it's ok. I'll build tonight if I haven't heard back from people.
