### ISSUE TITLE
Consider changing "you" in shortDesc to "I", to match the labels

### ISSUE THREAD

**Issue by BehindTheMath** [sdras/array-explorer#4]
The labels in [AppMethodPrimary.vue](https://github.com/sdras/array-explorer/blob/d1c5f0f39a8b75637b5a860f36f9c5b4be6ad150/src/components/AppMethodPrimary.vue) and [MethodChoice.vue](https://github.com/sdras/array-explorer/blob/d1c5f0f39a8b75637b5a860f36f9c5b4be6ad150/src/components/methods/MethodChoice.vue) use `I` (first person), whereas `shortDesc` in the [store](https://github.com/sdras/array-explorer/blob/a2fd72da31c1a573cb162bbea2a580b236b8b9b8/store/index.js) uses `you` (second person).

Perhaps the store should be changed to `I` to match the labels?

**Comment by sdras** [comment]
This is a really good point. I'll make the change soon.

**Comment by sdras** [comment]
This should be fixed now. It may need a chance to propogate to github pages docs.

**Comment by BehindTheMath** [comment]
BTW, if you write something like `Closes #4` or `Fixes #4` in the commit message, Github will close the issue automatically, and add a post under the issue referencing the commit that closed it.

https://help.github.com/articles/closing-issues-using-keywords/
