### ISSUE TITLE
As a newbie who comes across this site, I would like to know which programming language is being used. 

### ISSUE THREAD

**Issue by mikevallano** [sdras/array-explorer#43]
Currently, it doesn't mention JavaScript anywhere, so someone with no context wouldn't know which programming language this tool is using.

The readme mentions the possibility of adding additional programming language support, but for now, since it's only JavaScript, perhaps change the text from `Array Explorer` to `JavaScript Array Explorer`. 

Either way, this is an amazing tool. Thanks so much for building it!

**Comment by sdras** [comment]
Oh my goodness, you're so right! Sorry about that. This definitely needs to be included. Thanks for bringing it to my attention.

**Comment by sdras** [comment]
This is fixed! Thanks
