### ISSUE TITLE
Possible typo in English version

### ISSUE THREAD

**Issue by TheElderMindseeker** [sdras/array-explorer#45]
In `slice()` method description of English version of the service, the text states:

> The <code>slice()</code> method returns a shallow copy of a portion of an array into a new array object. You can specify either just the ending element (where begin will default to zero) or both the beginning and the end, comma-separated. The original array will not be modified.

But in fact, we cannot specify only ending element, but the beginning one. To prove my words I will refer to w3schools.com, admitting that the signature of the method is the following: `slice(start, end)`, where both parameters are optional. The `start` parameter comes first, so we cannot specify `end` parameter leaving the former out.

**Comment by sdras** [comment]
Good catch! That was an error on my part, I'll fix it up in the next version. Thanks!

**Comment by sdras** [comment]
This is fixed! Thanks
