### ISSUE TITLE
Browser Support or ECMAScript Specification Warning

### ISSUE THREAD

**Issue by stephenlcurtis** [sdras/array-explorer#51]
The tool contains array methods from ES5 up to ES7. A lot of these methods wouldn't work in IE11 for instance. Either the ECMAScript version or a ES6+ warning could let users know if they use said method they'd have to use a polyfill for pre-evergreen browser support or Node.js 4 or earlier.

**Comment by sdras** [comment]
This isn't documentation, so I leave that kind of detail to MDN. Thanks though.
