### ISSUE TITLE
excuse me...what it's is?

### ISSUE THREAD

**Issue by zhangenming** [sdras/array-explorer#75]
in store/index.js
```// create info about langauges
const languages = (ctx => {
  ....
})(require.context("./", true, /[a-z]{2}/));
```
What are these things?
when I `console.log(require.context) `or ` console.log(require)` it's get error
so Amazing... 
this code Related to webpack? or vue?

thanks

**Comment by alvaropinot** [comment]
It's probably https://www.npmjs.com/package/require-context, and it looks like it's used to load all the language files that matches the regex `/[a-z]{2}/` instead of loading them manually.

Hope it helps @zhangenming ☺️, and maybe @sdras can close this issue if it did. Better late than never 😅

**Comment by sdras** [comment]
yep!

**Comment by zhangenming** [comment]
2021~~
